<?php
/**
 * Title: 图标/分类/优势模块9
 * Slug: smartenterprise/icon9
 * Categories: icon
 * Block Types: core/template-part
 * Viewport Width: 1400
 */
?>
<!-- wp:themepark-block/themepark-area {"bottom":58,"top":46,"detects":"PcOnly","title":"丰富的技术沉淀","title2":"TECHNICAL PRECIPITATION","title1mode":"modle_title3","title2color":"#050505","title1size":28,"titleboder":0,"titletext":"行业领域内多年的默默耕耘，只为今天让我们骄傲的口碑。"} -->
<section class="wp-block-themepark-block-themepark-area block_layout thempark-block PcOnly" id="" style="padding-bottom:58px;padding-top:46px;" data-swiper-parallax="-700"><div class="block_layout_in"><div class="post_in_list_head modle_title3"><h3><span style="font-size:28px;" class="main-title ">丰富的技术沉淀</span><span style="color:#050505;" class="as-title ">TECHNICAL PRECIPITATION</span></h3><div class="title_boout"><div class="title_bo" style=""></div></div><font class="titletext" style="font-size:14px;"><span>行业领域内多年的默默耕耘，只为今天让我们骄傲的口碑。</span></font></div><!-- wp:column {"className":"block_layout_in"} -->
<div class="wp-block-column block_layout_in"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"33%"} -->
<div class="wp-block-column" style="flex-basis:33%"><!-- wp:themepark-block/themepark-icon {"txtf1":17,"txtc1":"#050505","iconl":1,"icon":[{"id":1620974737532,"text":"精准定位","text2":"二十年技术沉淀，高效定位目标人群\n快速找到目标客户","icon":"fas fa-user-friends","iconc":"#146ba2","icont":"","url":""},{"id":1620974737680,"text":"稳定提升","text2":"为超过2000家企业定制计划\n稳定提升","icon":"fas fa-chart-line","iconc":"#e21f2f","icont":"","url":""},{"id":1620976005051,"text":"技术支持","text2":"为超过500家企业提供稳定的售后技术支持\n稳定运行超过3600天","icon":"fas fa-check-circle","iconc":"#7fbb17","icont":"","url":""}],"margintop":0,"boxhi":73} -->
<section class="wp-block-themepark-block-themepark-icon thempark-block themepark_icon_list_out undefined" id="nomo" style="padding-bottom:20px;"><div class="themepark_icon_list_in"><div class="themepark_icon_lists iconl1"><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-user-friends" style="color:#146ba2;font-size:36px;"></i></div><b style="font-size:17px;color:#050505;">精准定位</b></div><div class="themepark_icon_box_d" style="font-size:14px;height:73px;"><span>二十年技术沉淀，高效定位目标人群</span><span>快速找到目标客户</span></div><div class="themepark_icon_box_bac" style=""></div></a><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-chart-line" style="color:#e21f2f;font-size:36px;"></i></div><b style="font-size:17px;color:#050505;">稳定提升</b></div><div class="themepark_icon_box_d" style="font-size:14px;height:73px;"><span>为超过2000家企业定制计划</span><span>稳定提升</span></div><div class="themepark_icon_box_bac" style=""></div></a><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-check-circle" style="color:#7fbb17;font-size:36px;"></i></div><b style="font-size:17px;color:#050505;">技术支持</b></div><div class="themepark_icon_box_d" style="font-size:14px;height:73px;"><span>为超过500家企业提供稳定的售后技术支持</span><span>稳定运行超过3600天</span></div><div class="themepark_icon_box_bac" style=""></div></a></div></div></section>
<!-- /wp:themepark-block/themepark-icon --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:themepark-block/themepark-imgtext {"bimg":[{"uploading":false,"date":1620974549000,"filename":"phone.png","menuOrder":0,"uploadedTo":2,"type":"image","subtype":"png","alt":"","title":"phone","caption":"","description":"","url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy6/uploads/2021/05/phone.png","id":83,"link":"<?php echo get_bloginfo('home');?>/index/phone/","author":"1","name":"phone","status":"inherit","modified":1620974549000,"mime":"image/png","icon":"<?php echo get_bloginfo('home');?>/wp-includes/images/media/default.png","dateFormatted":"2021年5月14日","nonces":{"update":"5350d65f2d","delete":"ac7687f304","edit":"4d2b95d919"},"editLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=83\u0026action=edit","meta":false,"authorName":"admin","authorLink":"<?php echo get_bloginfo('home');?>/wp-admin/profile.php","uploadedToTitle":"首页","uploadedToLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=2\u0026action=edit","filesizeInBytes":82875,"filesizeHumanReadable":"81 KB","context":"","height":545,"width":520,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy6/uploads/2021/05/phone-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":286,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy6/uploads/2021/05/phone-286x300.png","orientation":"portrait"},"full":{"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy6/uploads/2021/05/phone.png","height":545,"width":520,"orientation":"portrait"}},"compat":{"item":"","meta":""}}],"top":42,"bili":44,"modle":true,"leftright":false} -->
<section class="wp-block-themepark-block-themepark-imgtext thempark-block themepark_imgtext updonwmodle undefined" style="padding-top:42px;"><div class="themepark_imgtext_img" style="width:44%;"><img src="http://data.themepark.com.cn/2021/n/smartenterprise_data/qy6/uploads/2021/05/phone.png" alt=""/></div><div class="themepark_imgtext_text" style="width:53%;"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">我们致力于为各个行业提供MES、PLM、OA、IPD、体系建设、流程再造、管理提升等软件和服务</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div><div class="themepark_imgtext_ba" style="opacity:1;"></div></section>
<!-- /wp:themepark-block/themepark-imgtext --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"33%"} -->
<div class="wp-block-column" style="flex-basis:33%"><!-- wp:themepark-block/themepark-icon {"txtf1":17,"iconl":1,"icon":[{"id":1620974737532,"text":"安全保证","text2":"五年互联网加云安全服务\n全方位保证安全","icon":"fas fa-shield-alt","iconc":"#24b6b1","icont":"","url":""},{"id":1620974737680,"text":"稳定提升","text2":"为超过2000家企业定制计划\n稳定提升","icon":"fas fa-file-signature","iconc":"#b27630","icont":"","url":""},{"id":1620976284559,"text":"研发投入","text2":"为最新的云技术和云服务投入研发\n累积已取得56项技术专利","icon":"fas fa-microscope","iconc":"#f29900","icont":"","url":""}],"margintop":0,"boxhi":73} -->
<section class="wp-block-themepark-block-themepark-icon thempark-block themepark_icon_list_out undefined" id="nomo" style="padding-bottom:20px;"><div class="themepark_icon_list_in"><div class="themepark_icon_lists iconl1"><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-shield-alt" style="color:#24b6b1;font-size:36px;"></i></div><b style="font-size:17px;">安全保证</b></div><div class="themepark_icon_box_d" style="font-size:14px;height:73px;"><span>五年互联网加云安全服务</span><span>全方位保证安全</span></div><div class="themepark_icon_box_bac" style=""></div></a><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-file-signature" style="color:#b27630;font-size:36px;"></i></div><b style="font-size:17px;">稳定提升</b></div><div class="themepark_icon_box_d" style="font-size:14px;height:73px;"><span>为超过2000家企业定制计划</span><span>稳定提升</span></div><div class="themepark_icon_box_bac" style=""></div></a><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-microscope" style="color:#f29900;font-size:36px;"></i></div><b style="font-size:17px;">研发投入</b></div><div class="themepark_icon_box_d" style="font-size:14px;height:73px;"><span>为最新的云技术和云服务投入研发</span><span>累积已取得56项技术专利</span></div><div class="themepark_icon_box_bac" style=""></div></a></div></div></section>
<!-- /wp:themepark-block/themepark-icon --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:column --></div><div class="layout_badh"></div></section>
<!-- /wp:themepark-block/themepark-area -->