<?php
/**
 * Title:网站底部模块1
 * Slug: smartenterprise/webfoot1
 * Categories: webfoot
 * Block Types: core/template-part
 * Viewport Width: 1400
 */
?>
<!-- wp:themepark-block/themepark-area {"bcolor":"#1a1a1a","bimgp2":true,"bottom":21,"top":21} -->
<section class="wp-block-themepark-block-themepark-area block_layout thempark-block undefined" id="" style="background-color:#1a1a1a;padding-bottom:21px;padding-top:21px;" data-swiper-parallax="-700"><div class="block_layout_in"><!-- wp:column {"className":"block_layout_in"} -->
<div class="wp-block-column block_layout_in"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":""} -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-listbox {"title":"我们的联络方式","titlecolor":"#f29900","titlesize":18,"bpadding":0,"bpadding2":7,"border":"#0071a1","listcolor":"#ffffff","listm":10,"icon":[{"text":"湖南省长沙市天心区芙蓉中路三段建鸿达现代空间1705","icon":"fas fa-map-marker","url":""},{"text":"TEL:0731-8888xxxxx","icon":"fas fa-phone","url":""},{"text":"E-mail:XXXX@THEMEPARK.COM","icon":"fas fa-envelope","url":""},{"text":"手机：1589999XXXX","icon":"fas fa-phone","url":""}],"iconcolor":"#f29900","boderright":false,"bodercolor":"#666666","className":"undefined padingmodle"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox  undefined padingmodle" style=""><h3 class="themepark_listbox_title" style="color:#f29900;font-size:18px;padding-left:0%;padding-right:7%;"><span>我们的联络方式</span></h3><ul class="themepark_listbox_list" style="padding-left:0%;padding-right:7%;"><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:10px;padding-left:29px;"><i class="fas fa-map-marker" style="color:#f29900;line-height:24px"></i><span>湖南省长沙市天心区芙蓉中路三段建鸿达现代空间1705</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:10px;padding-left:29px;"><i class="fas fa-phone" style="color:#f29900;line-height:24px"></i><span>TEL:0731-8888xxxxx</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:10px;padding-left:29px;"><i class="fas fa-envelope" style="color:#f29900;line-height:24px"></i><span>E-mail:XXXX@THEMEPARK.COM</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:10px;padding-left:29px;"><i class="fas fa-phone" style="color:#f29900;line-height:24px"></i><span>手机：1589999XXXX</span></li></ul><div class="themepark_listbox_ba" style="opacity:1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"25%"} -->
<div class="wp-block-column" style="flex-basis:25%"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-listbox {"title":"了解我们","titlecolor":"#f29900","titlesize":18,"detects":"PcOnly","bpadding":8,"border":"#666666","listcolor":"#afafaf","listsize":16,"listm":8,"icon":[{"text":"关于我们","icon":"","url":"#"},{"text":"隐私政策","icon":"","url":""},{"text":"联系我们","icon":"","url":"#"},{"text":"常见问题","icon":"","url":"#"}],"iconcolor":"#f29900","boderleft":false,"boderright":false,"bodercolor":"#666666","className":"undefined"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox PcOnly undefined" style=""><h3 class="themepark_listbox_title" style="color:#f29900;font-size:18px;padding-left:8%;padding-right:2%;"><span>了解我们</span></h3><ul class="themepark_listbox_list" style="padding-left:8%;padding-right:2%;"><li style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><a href="#"></a><a href="#" style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><span>关于我们</span></a></li><li style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><span>隐私政策</span></li><li style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><a href="#"></a><a href="#" style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><span>联系我们</span></a></li><li style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><a href="#"></a><a href="#" style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><span>常见问题</span></a></li></ul><div class="themepark_listbox_ba" style="opacity:1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-listbox {"title":"客户服务","titlecolor":"#f29900","titlesize":18,"detects":"PcOnly","bpadding":8,"border":"#666666","listcolor":"#afafaf","listsize":16,"listm":8,"icon":[{"text":"服务条款","icon":"","url":"#"},{"text":"退款政策和帮助","icon":"","url":""},{"text":"文档帮助下载","icon":"","url":"#"},{"text":"联系客服","icon":"","url":"#"}],"iconcolor":"#f29900","boderleft":false,"boderright":false,"bodercolor":"#666666","className":"undefined"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox PcOnly undefined" style=""><h3 class="themepark_listbox_title" style="color:#f29900;font-size:18px;padding-left:8%;padding-right:2%;"><span>客户服务</span></h3><ul class="themepark_listbox_list" style="padding-left:8%;padding-right:2%;"><li style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><a href="#"></a><a href="#" style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><span>服务条款</span></a></li><li style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><span>退款政策和帮助</span></li><li style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><a href="#"></a><a href="#" style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><span>文档帮助下载</span></a></li><li style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><a href="#"></a><a href="#" style="color:#afafaf;font-size:16px;line-height:26px;margin-bottom:8px;"><span>联系客服</span></a></li></ul><div class="themepark_listbox_ba" style="opacity:1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-listbox {"title":"从这里关注我们","titlecolor":"#f29900","titlesize":18,"iconmodle":true,"bpadding":8,"border":"#666666","listcolor":"#666666","listsize":21,"listm":8,"icon":[{"text":"亚马逊","icon":"fab fa-amazon","url":"#"},{"text":"安卓市场","icon":"fab fa-android","url":""},{"text":"AppStore","icon":"fab fa-apple","url":"#"},{"text":"微博","icon":"fab fa-weibo","url":"#"},{"text":"facebook","icon":"fab fa-facebook-square","url":""},{"text":"twitter","icon":"fab fa-twitter-square","url":""}],"iconcolor":"#f29900","boderleft":false,"boderright":false,"bodercolor":"#666666","className":"true"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox iconmodle  true" style=""><h3 class="themepark_listbox_title" style="color:#f29900;font-size:18px;padding-left:8%;padding-right:2%;"><span>从这里关注我们</span></h3><ul class="themepark_listbox_list" style="padding-left:8%;padding-right:2%;"><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><a href="#"><i class="fab fa-amazon" style="color:#fff;line-height:31px"></i></a><a href="#" style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><span>亚马逊</span></a></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><i class="fab fa-android" style="color:#fff;line-height:31px"></i><span>安卓市场</span></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><a href="#"><i class="fab fa-apple" style="color:#fff;line-height:31px"></i></a><a href="#" style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><span>AppStore</span></a></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><a href="#"><i class="fab fa-weibo" style="color:#fff;line-height:31px"></i></a><a href="#" style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><span>微博</span></a></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><i class="fab fa-facebook-square" style="color:#fff;line-height:31px"></i><span>facebook</span></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><i class="fab fa-twitter-square" style="color:#fff;line-height:31px"></i><span>twitter</span></li></ul><div class="themepark_listbox_ba" style="opacity:1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox -->

<!-- wp:themepark-block/themepark-listbox {"title":"付款支持","titlecolor":"#f29900","titlesize":18,"iconmodle":true,"bpadding":8,"border":"#666666","listcolor":"#666666","listsize":21,"listm":8,"icon":[{"text":"支付宝","icon":"fab fa-alipay","url":"#"},{"text":"amazon pay","icon":"fab fa-amazon-pay","url":""},{"text":"cc-visa","icon":"fab fa-cc-visa","url":"#"},{"text":"paypal","icon":"fab fa-cc-paypal","url":"#"},{"text":"微信支付","icon":"fab fa-weixin","url":""}],"iconcolor":"#f29900","boderleft":false,"boderright":false,"bodercolor":"#666666","className":"true"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox iconmodle  true" style=""><h3 class="themepark_listbox_title" style="color:#f29900;font-size:18px;padding-left:8%;padding-right:2%;"><span>付款支持</span></h3><ul class="themepark_listbox_list" style="padding-left:8%;padding-right:2%;"><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><a href="#"><i class="fab fa-alipay" style="color:#fff;line-height:31px"></i></a><a href="#" style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><span>支付宝</span></a></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><i class="fab fa-amazon-pay" style="color:#fff;line-height:31px"></i><span>amazon pay</span></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><a href="#"><i class="fab fa-cc-visa" style="color:#fff;line-height:31px"></i></a><a href="#" style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><span>cc-visa</span></a></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><a href="#"><i class="fab fa-cc-paypal" style="color:#fff;line-height:31px"></i></a><a href="#" style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><span>paypal</span></a></li><li style="background-color:#666666;color:#fff;font-size:21px;line-height:31px;margin-bottom:8px;"><i class="fab fa-weixin" style="color:#fff;line-height:31px"></i><span>微信支付</span></li></ul><div class="themepark_listbox_ba" style="opacity:1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column -->

<!-- wp:column {"width":""} -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-imgtext {"bimg":[{"id":86,"title":"weixin3","filename":"weixin3.png","url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy1/uploads/2019/04/weixin3.png","link":"<?php echo get_bloginfo('home');?>/weixin3","alt":"","author":"1","description":"\t\t\t\t\t\t","caption":"\t\t\t\t\t\t","name":"weixin3","status":"inherit","uploadedTo":0,"date":"2019-04-23T06:56:57.000Z","modified":"2020-09-25T07:41:37.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"<?php echo get_bloginfo('home');?>/wp-includes/images/media/default.png","dateFormatted":"2019年4月23日","nonces":{"update":"d52ff1750d","delete":"ea28f898e9","edit":"13cb5caa04"},"editLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=86\u0026action=edit","meta":false,"authorName":"admin","authorLink":"<?php echo get_bloginfo('home');?>/wp-admin/profile.php","filesizeInBytes":30830,"filesizeHumanReadable":"30 KB","context":"","height":138,"width":284,"orientation":"landscape","sizes":{"thumbnail":{"height":138,"width":150,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy1/uploads/2019/04/weixin3-150x138.png","orientation":"landscape"},"full":{"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy1/uploads/2019/04/weixin3.png","height":138,"width":284,"orientation":"landscape"}},"compat":{"item":"","meta":""}}],"top":17,"modle":true,"leftright":true,"textalign2":"left","detects":"PcOnly"} -->
<section class="wp-block-themepark-block-themepark-imgtext thempark-block themepark_imgtext updonwmodle leftright PcOnly" style="padding-top:17px;"><div class="themepark_imgtext_text" style=""><!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":3,"style":{"color":{"text":"#f29900"},"typography":{"fontSize":18}}} -->
<h3 class="has-text-color" style="color:#f29900;font-size:18px">关注公众号</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div><div class="themepark_imgtext_img" style="text-align:left;"><img src="http://data.themepark.com.cn/2021/n/smartenterprise_data/qy1/uploads/2019/04/weixin3.png" alt=""/></div><div class="themepark_imgtext_ba" style="opacity:1;"></div></section>
<!-- /wp:themepark-block/themepark-imgtext --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:column --></div><div class="layout_badh"></div></section>
<!-- /wp:themepark-block/themepark-area -->