<?php
/**
 * Title: 图标/分类/优势模块8
 * Slug: smartenterprise/icon8
 * Categories: icon
 * Block Types: core/template-part
 * Viewport Width: 1400
 */
?>
<!-- wp:themepark-block/themepark-icon {"txtc1":"#666666","txtc2":"#666666","iconf":32,"icont":"nomo3","bc1o":68,"icon":[{"id":1635920009226,"text":"价格透明","text2":"明码标价 无捆绑销售","icon":"fas fa-balance-scale","iconc":"#24b6b1","icont":"","url":"","svg":""},{"id":1635923949922,"text":"信息保密","text2":"保护个人和企业信息不泄露","icon":"fas fa-shield-alt","iconc":"#0799f3","icont":"","url":""},{"id":1635923950071,"text":"进度掌控","text2":"7*24h专业客服，随时解决问题","icon":"fas fa-user-tie","iconc":"#f29900","icont":"","url":""},{"id":1635923951595,"text":"售后无忧","text2":"售后保障全程无忧","icon":"fas fa-umbrella","iconc":"#77ba03","icont":"","url":""}],"marginbottm":5,"margintop":10,"b2":"#ffffff"} -->
<section class="wp-block-themepark-block-themepark-icon thempark-block themepark_icon_list_out undefined" id="nomo3" style="padding-bottom:5px;padding-top:10px;background:#ffffff;"><div class="themepark_icon_list_in"><div class="themepark_icon_lists iconl4"><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-balance-scale" style="color:#24b6b1;font-size:32px;"></i></div></div><div class="themepark_icon_box_d" style="font-size:14px;color:#666666;"><b style="font-size:16px;color:#666666;">价格透明</b><span>明码标价 无捆绑销售</span></div><div class="themepark_icon_box_bac" style="opacity:0.68;"></div></a><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-shield-alt" style="color:#0799f3;font-size:32px;"></i></div></div><div class="themepark_icon_box_d" style="font-size:14px;color:#666666;"><b style="font-size:16px;color:#666666;">信息保密</b><span>保护个人和企业信息不泄露</span></div><div class="themepark_icon_box_bac" style="opacity:0.68;"></div></a><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-user-tie" style="color:#f29900;font-size:32px;"></i></div></div><div class="themepark_icon_box_d" style="font-size:14px;color:#666666;"><b style="font-size:16px;color:#666666;">进度掌控</b><span>7*24h专业客服，随时解决问题</span></div><div class="themepark_icon_box_bac" style="opacity:0.68;"></div></a><a class="themepark_icon_box undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-umbrella" style="color:#77ba03;font-size:32px;"></i></div></div><div class="themepark_icon_box_d" style="font-size:14px;color:#666666;"><b style="font-size:16px;color:#666666;">售后无忧</b><span>售后保障全程无忧</span></div><div class="themepark_icon_box_bac" style="opacity:0.68;"></div></a></div></div></section>
<!-- /wp:themepark-block/themepark-icon -->