<?php
/**
 * Title:网站底部模块9
 * Slug: smartenterprise/webfoot9
 * Categories: webfoot
 * Block Types: core/template-part
 * Viewport Width: 1400
 */
?>
<!-- wp:themepark-block/themepark-area {"bcolor":"#e21f2f","bimg":[{"uploading":false,"date":1639731612000,"filename":"bott.jpg","menuOrder":0,"uploadedTo":275,"type":"image","subtype":"jpeg","id":281,"title":"bott","url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/bott.jpg","link":"<?php echo get_bloginfo('home');?>/block_temp/网站底部模板/bott/","alt":"","author":"1","description":"","caption":"","name":"bott","status":"inherit","modified":1639731612000,"mime":"image/jpeg","icon":"<?php echo get_bloginfo('home');?>/wp-includes/images/media/default.png","dateFormatted":"2021年12月17日","nonces":{"update":"22540a19b5","delete":"ee28af0ac1","edit":"7cd22c861c"},"editLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=281\u0026action=edit","meta":false,"authorName":"admin","authorLink":"<?php echo get_bloginfo('home');?>/wp-admin/profile.php","uploadedToTitle":"网站底部模板","uploadedToLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=275\u0026action=edit","filesizeInBytes":79834,"filesizeHumanReadable":"78 KB","context":"","height":400,"width":1920,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/bott-150x150.jpg","orientation":"landscape"},"medium":{"height":63,"width":300,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/bott-300x63.jpg","orientation":"landscape"},"large":{"height":213,"width":1024,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/bott-1024x213.jpg","orientation":"landscape"},"full":{"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/bott.jpg","height":400,"width":1920,"orientation":"landscape"}},"compat":{"item":"","meta":""}}],"bimgp2":true,"bimgp4":"center","top":40,"className":"top20"} -->
<section class="wp-block-themepark-block-themepark-area block_layout thempark-block undefined  top20" id="" style="background-color:#e21f2f;padding-top:40px;" data-swiper-parallax="-700"><div class="block_layout_in"><!-- wp:column {"className":"block_layout_in"} -->
<div class="wp-block-column block_layout_in"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"35%","className":"PcOnly"} -->
<div class="wp-block-column PcOnly" style="flex-basis:35%"><!-- wp:themepark-block/themepark-listbox {"title":"关于我们","titlecolor":"#ffffff","titlesize":18,"bottom":25,"top":10,"bcolor":"#000000","bcolorop":10,"bpadding":3,"bpadding2":5,"listcolor":"#ffffff","listsize":13,"listm":17,"icon":[{"text":"THEMEPARK有限公司是集工商服务、财税代理、税务筹划、知识产权、项目申报、金融服务、网站建设、微信小程序开发、品牌策划、品牌设计、新媒体运营、社保代缴等企业服务。同时打通线下园区、孵化器等实体产业，助力国内中小企业完成从0到1的发展。","icon":"","url":""}],"iconcolor":"#ffffff"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox" style="padding-bottom:25px;padding-top:10px;"><h3 class="themepark_listbox_title" style="color:#ffffff;font-size:18px;padding-left:3%;padding-right:5%;"><span>关于我们</span></h3><ul class="themepark_listbox_list" style="padding-left:3%;padding-right:5%;"><li style="color:#ffffff;font-size:13px;line-height:23px;margin-bottom:17px;"><span>THEMEPARK有限公司是集工商服务、财税代理、税务筹划、知识产权、项目申报、金融服务、网站建设、微信小程序开发、品牌策划、品牌设计、新媒体运营、社保代缴等企业服务。同时打通线下园区、孵化器等实体产业，助力国内中小企业完成从0到1的发展。</span></li></ul><div class="themepark_listbox_ba" style="background-color:#000000;opacity:0.1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"28%"} -->
<div class="wp-block-column" style="flex-basis:28%"><!-- wp:themepark-block/themepark-listbox {"title":"联系我们","titlecolor":"#ffffff","titlesize":18,"bottom":24,"top":10,"bcolor":"#000000","bcolorop":10,"bpadding":5,"bpadding2":0,"listcolor":"#ffffff","icon":[{"text":"深圳市福田区紫竹七道8号 \n上海市宝山区逸仙路与何家湾路交叉口","icon":"fas fa-map-marker-alt","url":""},{"text":"咨询热线：158 1234 5678","icon":"fas fa-mobile-alt","url":""},{"text":"xxx#@xxx.com","icon":"fas fa-envelope","url":"mailto:info@chenyanglobal.com"}],"iconcolor":"#ffffff"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox" style="padding-bottom:24px;padding-top:10px;"><h3 class="themepark_listbox_title" style="color:#ffffff;font-size:18px;padding-left:5%;padding-right:0%;"><span>联系我们</span></h3><ul class="themepark_listbox_list" style="padding-left:5%;padding-right:0%;"><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-map-marker-alt" style="color:#ffffff;line-height:24px"></i><span>深圳市福田区紫竹七道8号 </span><span>上海市宝山区逸仙路与何家湾路交叉口</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-mobile-alt" style="color:#ffffff;line-height:24px"></i><span>咨询热线：158 1234 5678</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><a href="mailto:info@chenyanglobal.com"><i class="fas fa-envelope" style="color:#ffffff;line-height:24px"></i></a><a href="mailto:info@chenyanglobal.com" style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;"><span>xxx#@xxx.com</span></a></li></ul><div class="themepark_listbox_ba" style="background-color:#000000;opacity:0.1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"20%"} -->
<div class="wp-block-column" style="flex-basis:20%"><!-- wp:themepark-block/themepark-listbox {"title":"服务产品","titlecolor":"#ffffff","titlesize":18,"bottom":41,"top":10,"bcolor":"#000000","bcolorop":10,"bpadding":7,"bpadding2":0,"listcolor":"#ffffff","icon":[{"text":"代理记账","icon":"fas fa-chevron-circle-right","url":""},{"text":"工商服务","icon":"fas fa-chevron-circle-right","url":""},{"text":"公司注册","icon":"fas fa-chevron-circle-right","url":"mailto:info@chenyanglobal.com"},{"text":"知识产权","icon":"","url":""},{"text":"社保代办","icon":"","url":""}],"iconcolor":"#ffffff"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox" style="padding-bottom:41px;padding-top:10px;"><h3 class="themepark_listbox_title" style="color:#ffffff;font-size:18px;padding-left:7%;padding-right:0%;"><span>服务产品</span></h3><ul class="themepark_listbox_list" style="padding-left:7%;padding-right:0%;"><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i><span>代理记账</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i><span>工商服务</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><a href="mailto:info@chenyanglobal.com"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i></a><a href="mailto:info@chenyanglobal.com" style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;"><span>公司注册</span></a></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i><span>知识产权</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i><span>社保代办</span></li></ul><div class="themepark_listbox_ba" style="background-color:#000000;opacity:0.1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"20%"} -->
<div class="wp-block-column" style="flex-basis:20%"><!-- wp:themepark-block/themepark-listbox {"title":"服务产品","titlecolor":"#ffffff","titlesize":18,"bottom":41,"top":10,"bcolor":"#000000","bcolorop":10,"bpadding":7,"bpadding2":0,"listcolor":"#ffffff","icon":[{"text":"代理记账","icon":"fas fa-chevron-circle-right","url":""},{"text":"工商服务","icon":"fas fa-chevron-circle-right","url":""},{"text":"公司注册","icon":"fas fa-chevron-circle-right","url":"mailto:info@chenyanglobal.com"},{"text":"知识产权","icon":"","url":""},{"text":"社保代办","icon":"","url":""}],"iconcolor":"#ffffff"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox" style="padding-bottom:41px;padding-top:10px;"><h3 class="themepark_listbox_title" style="color:#ffffff;font-size:18px;padding-left:7%;padding-right:0%;"><span>服务产品</span></h3><ul class="themepark_listbox_list" style="padding-left:7%;padding-right:0%;"><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i><span>代理记账</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i><span>工商服务</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><a href="mailto:info@chenyanglobal.com"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i></a><a href="mailto:info@chenyanglobal.com" style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;"><span>公司注册</span></a></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i><span>知识产权</span></li><li style="color:#ffffff;font-size:14px;line-height:24px;margin-bottom:3px;padding-left:29px;"><i class="fas fa-chevron-circle-right" style="color:#ffffff;line-height:24px"></i><span>社保代办</span></li></ul><div class="themepark_listbox_ba" style="background-color:#000000;opacity:0.1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:column --></div><div class="layout_badh"><div class="PcOnly themepark-block_layout_ba lazyload swiper-lazy " style="background-size:cover;background-position:center;" data-src="http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/bott.jpg"></div></div></section>
<!-- /wp:themepark-block/themepark-area -->