<?php
/**
 * Title:网站底部模块2
 * Slug: smartenterprise/webfoot2
 * Categories: webfoot
 * Block Types: core/template-part
 * Viewport Width: 1400
 */
?>
<!-- wp:themepark-block/themepark-icon {"txtf1":18,"txtc1":"#0e0e0e","txtc2":"#666666","iconf":33,"iconl":3,"icont":"nomo3","bc1":"#ffffff","icon":[{"id":1616568787613,"text":"Pre sales telephone number","text2":" 84 400 888 ****","icon":"fas fa-phone-square-alt","iconc":"#32abf6","icont":"","url":"","svg":""},{"id":1616571502460,"text":"Contact email address","text2":"info@themeparkss.cc","icon":"fas fa-envelope-square","iconc":"#32abf6","icont":"","url":""},{"id":1616569171225,"text":"24/7 Helpline Support ","text2":"call:  86 2345 6789","icon":"fas fa-user-friends","iconc":"#32abf6","icont":"","url":""}],"marginbottm":0,"margintop":10,"b2":"#ffffff","boxhi":49} -->
<section class="wp-block-themepark-block-themepark-icon thempark-block themepark_icon_list_out undefined" id="nomo3" style="padding-top:10px;background:#ffffff;"><div class="themepark_icon_list_in"><div class="themepark_icon_lists iconl3"><a class="themepark_icon_box bhclas undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-phone-square-alt" style="color:#32abf6;font-size:33px;"></i></div></div><div class="themepark_icon_box_d" style="font-size:14px;color:#666666;height:49px;"><b style="font-size:18px;color:#0e0e0e;">Pre sales telephone number</b><span> 84 400 888 ****</span></div><div class="themepark_icon_box_bac" style="background:#ffffff;"></div></a><a class="themepark_icon_box bhclas undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-envelope-square" style="color:#32abf6;font-size:33px;"></i></div></div><div class="themepark_icon_box_d" style="font-size:14px;color:#666666;height:49px;"><b style="font-size:18px;color:#0e0e0e;">Contact email address</b><span>info@themeparkss.cc</span></div><div class="themepark_icon_box_bac" style="background:#ffffff;"></div></a><a class="themepark_icon_box bhclas undefined" href=""><div class="themepark_icon_box_i"><div class="themepark_icon_box_i_out"><i class="fas fa-user-friends" style="color:#32abf6;font-size:33px;"></i></div></div><div class="themepark_icon_box_d" style="font-size:14px;color:#666666;height:49px;"><b style="font-size:18px;color:#0e0e0e;">24/7 Helpline Support </b><span>call:  86 2345 6789</span></div><div class="themepark_icon_box_bac" style="background:#ffffff;"></div></a></div></div></section>
<!-- /wp:themepark-block/themepark-icon -->

<!-- wp:themepark-block/themepark-area {"bcolor":"#32abf6","bottom":15,"top":15} -->
<section class="wp-block-themepark-block-themepark-area block_layout thempark-block undefined" id="" style="background-color:#32abf6;padding-bottom:15px;padding-top:15px;" data-swiper-parallax="-700"><div class="block_layout_in"><!-- wp:column {"className":"block_layout_in"} -->
<div class="wp-block-column block_layout_in"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"48%"} -->
<div class="wp-block-column" style="flex-basis:48%"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-imgtext {"bimg":[{"uploading":false,"date":1616839865000,"filename":"logobottom2.png","menuOrder":0,"uploadedTo":639,"type":"image","subtype":"png","id":650,"title":"logobottom2","url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy2/uploads/2021/03/logobottom2.png","link":"<?php echo get_bloginfo('home');?>/block_temp/网站底部/logobottom2/","alt":"","author":"1","description":"","caption":"","name":"logobottom2","status":"inherit","modified":1616839865000,"mime":"image/png","icon":"<?php echo get_bloginfo('home');?>/wp-includes/images/media/default.png","dateFormatted":"2021年3月27日","nonces":{"update":"a25727a36f","delete":"7cccb44842","edit":"34cb66a9c7"},"editLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=650\u0026action=edit","meta":false,"authorName":"admin","authorLink":"<?php echo get_bloginfo('home');?>/wp-admin/profile.php","uploadedToTitle":"网站底部","uploadedToLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=639\u0026action=edit","filesizeInBytes":6343,"filesizeHumanReadable":"6 KB","context":"","height":85,"width":400,"orientation":"landscape","sizes":{"thumbnail":{"height":85,"width":150,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy2/uploads/2021/03/logobottom2-150x85.png","orientation":"landscape"},"medium":{"height":64,"width":300,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy2/uploads/2021/03/logobottom2-300x64.png","orientation":"landscape"},"full":{"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy2/uploads/2021/03/logobottom2.png","height":85,"width":400,"orientation":"landscape"}},"compat":{"item":"","meta":""}}],"top":38,"bcolorop":76,"bpadding":false,"modle":true,"textalign2":"left"} -->
<section class="wp-block-themepark-block-themepark-imgtext thempark-block themepark_imgtext updonwmodle undefined" style="padding-top:38px;"><div class="themepark_imgtext_img" style="text-align:left;"><img src="http://data.themepark.com.cn/2021/n/smartenterprise_data/qy2/uploads/2021/03/logobottom2.png" alt=""/></div><div class="themepark_imgtext_text" style=""><!-- wp:column -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-wright {"font":16,"font2":26,"font4":"#ffffff","font9":14} -->
<div class="wp-block-themepark-block-themepark-wright content-super-p" style="font-size:16px;line-height:26px;color:#ffffff;padding:10px 14px;"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Labortech will be administered through customizable programs incorporate partnership between family illness or disease management. Labortech Made With Latest Technology Bootstrap 5.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:themepark-block/themepark-wright --></div>
<!-- /wp:column --></div><div class="themepark_imgtext_ba" style="opacity:0.76;"></div></section>
<!-- /wp:themepark-block/themepark-imgtext -->

<!-- wp:themepark-block/themepark-listbox {"titlesize":10,"top":15,"iconmodle":true,"bpadding2":0,"listcolor":"#146ba2","listsize":18,"icon":[{"text":"facebook","icon":"fab fa-facebook-f","url":"#"},{"text":"linkedin","icon":"fab fa-linkedin-in","url":"#"},{"text":"telegram","icon":"fab fa-telegram-plane","url":"#"},{"text":"twitter","icon":"fab fa-twitter","url":"#"}],"iconcolor":"#ffffff"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox iconmodle" style="padding-top:15px;"><ul class="themepark_listbox_list" style="padding-left:2%;padding-right:0%;"><li style="background-color:#146ba2;color:#fff;font-size:18px;line-height:28px;margin-bottom:3px;"><a href="#"><i class="fab fa-facebook-f" style="color:#fff;line-height:28px"></i></a><a href="#" style="background-color:#146ba2;color:#fff;font-size:18px;line-height:28px;margin-bottom:3px;"><span>facebook</span></a></li><li style="background-color:#146ba2;color:#fff;font-size:18px;line-height:28px;margin-bottom:3px;"><a href="#"><i class="fab fa-linkedin-in" style="color:#fff;line-height:28px"></i></a><a href="#" style="background-color:#146ba2;color:#fff;font-size:18px;line-height:28px;margin-bottom:3px;"><span>linkedin</span></a></li><li style="background-color:#146ba2;color:#fff;font-size:18px;line-height:28px;margin-bottom:3px;"><a href="#"><i class="fab fa-telegram-plane" style="color:#fff;line-height:28px"></i></a><a href="#" style="background-color:#146ba2;color:#fff;font-size:18px;line-height:28px;margin-bottom:3px;"><span>telegram</span></a></li><li style="background-color:#146ba2;color:#fff;font-size:18px;line-height:28px;margin-bottom:3px;"><a href="#"><i class="fab fa-twitter" style="color:#fff;line-height:28px"></i></a><a href="#" style="background-color:#146ba2;color:#fff;font-size:18px;line-height:28px;margin-bottom:3px;"><span>twitter</span></a></li></ul><div class="themepark_listbox_ba" style="opacity:1;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"15%"} -->
<div class="wp-block-column" style="flex-basis:15%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-listbox {"title":"SERVICES","titlecolor":"#ffffff","titlesize":23,"detects":"PcOnly","bottom":27,"bcolorop":76,"listcolor":"#ffffff","listsize":16,"listm":7,"icon":[{"text":"Pathologycam Testing","icon":"fas fa-chevron-circle-right","url":"#"},{"text":"Biochemistry Solution","icon":"","url":"#"},{"text":"Chemical Research","icon":"","url":""},{"text":"Pharmaceutical Research","icon":"","url":""},{"text":"Diabetes Testing","icon":"","url":""},{"text":"Terms \u0026 Condition","icon":"","url":""}],"iconcolor":"#146ba2","boderup":false,"boderdonw":false,"boderleft":false,"boderright":false,"bodercolor":"#ffffff"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox PcOnly" style="padding-bottom:27px;"><h3 class="themepark_listbox_title" style="color:#ffffff;font-size:23px;padding-left:2%;padding-right:2%;"><span>SERVICES</span></h3><ul class="themepark_listbox_list" style="padding-left:2%;padding-right:2%;"><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><a href="#"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i></a><a href="#" style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;"><span>Pathologycam Testing</span></a></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><a href="#"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i></a><a href="#" style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;"><span>Biochemistry Solution</span></a></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i><span>Chemical Research</span></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i><span>Pharmaceutical Research</span></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i><span>Diabetes Testing</span></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i><span>Terms &amp; Condition</span></li></ul><div class="themepark_listbox_ba" style="opacity:0.76;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:themepark-block/themepark-listbox {"title":"SERVICES","titlecolor":"#ffffff","titlesize":23,"detects":"PcOnly","bottom":27,"bcolorop":76,"listcolor":"#ffffff","listsize":16,"listm":7,"icon":[{"text":"Pathologycam Testing","icon":"fas fa-chevron-circle-right","url":"#"},{"text":"Biochemistry Solution","icon":"","url":"#"},{"text":"Chemical Research","icon":"","url":""},{"text":"Pharmaceutical Research","icon":"","url":""},{"text":"Diabetes Testing","icon":"","url":""},{"text":"Terms \u0026 Condition","icon":"","url":""}],"iconcolor":"#146ba2","boderup":false,"boderdonw":false,"boderleft":false,"boderright":false,"bodercolor":"#ffffff"} -->
<section class="wp-block-themepark-block-themepark-listbox thempark-block themepark_listbox PcOnly" style="padding-bottom:27px;"><h3 class="themepark_listbox_title" style="color:#ffffff;font-size:23px;padding-left:2%;padding-right:2%;"><span>SERVICES</span></h3><ul class="themepark_listbox_list" style="padding-left:2%;padding-right:2%;"><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><a href="#"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i></a><a href="#" style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;"><span>Pathologycam Testing</span></a></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><a href="#"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i></a><a href="#" style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;"><span>Biochemistry Solution</span></a></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i><span>Chemical Research</span></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i><span>Pharmaceutical Research</span></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i><span>Diabetes Testing</span></li><li style="color:#ffffff;font-size:16px;line-height:26px;margin-bottom:7px;padding-left:31px;"><i class="fas fa-chevron-circle-right" style="color:#146ba2;line-height:26px"></i><span>Terms &amp; Condition</span></li></ul><div class="themepark_listbox_ba" style="opacity:0.76;"></div></section>
<!-- /wp:themepark-block/themepark-listbox --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:column --></div><div class="layout_badh"></div></section>
<!-- /wp:themepark-block/themepark-area -->