<?php
/**
 * Title: 网站头部模式6
 * Slug: smartenterprise/webhead6
 * Categories: webhead
 * Block Types: core/template-part
 * Viewport Width: 1400
 */
?>
<!-- wp:themepark-block/themepark-header {"headinfo":[{"module":"3","navtext":16,"navb":false,"navpd":33,"navc1":"#666666","navc2":"#ffffff","navc3":"#e21f2f","navc4":"#ffffff","navc5":"#fafafa","navc6":"","topc1":"","topc2":"","topf":"","seach1":"","seach2":"","search1":"#e21f2f","sub":217,"navlib":false}],"icontext":[{"title":"服务咨询热线","text":"158-1234-567","url":"","icon":"fas fa-phone","color":"#146ba2"},{"title":"覆盖全国多个城市","text":"长沙 . 武汉 . 成都 . 重庆...","url":"","icon":"fas fa-map-marker-alt","color":"#f29900"},{"title":"在线客服","text":"点击联系","url":"","icon":"fab fa-weixin","color":"#75b900"}],"hidesearch":true,"logoimg":[{"id":7,"title":"logo","filename":"logo.png","url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/logo.png","link":"<?php echo get_bloginfo('home');?>/block_temp/网站头部模板/logo/","alt":"","author":"1","description":"","caption":"","name":"logo","status":"inherit","uploadedTo":5,"date":"2021-12-15T06:26:24.000Z","modified":"2021-12-15T06:26:24.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"<?php echo get_bloginfo('home');?>/wp-includes/images/media/default.png","dateFormatted":"2021年12月15日","nonces":{"update":"3d5063826d","delete":"f3f3aea37e","edit":"e5a03cdd06"},"editLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=7\u0026action=edit","meta":false,"authorName":"admin","authorLink":"<?php echo get_bloginfo('home');?>/wp-admin/profile.php","uploadedToTitle":"网站头部模板","uploadedToLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=5\u0026action=edit","filesizeInBytes":8598,"filesizeHumanReadable":"8 KB","context":"","height":133,"width":434,"orientation":"landscape","sizes":{"thumbnail":{"height":133,"width":150,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/logo-150x133.png","orientation":"landscape"},"medium":{"height":92,"width":300,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/logo-300x92.png","orientation":"landscape"},"full":{"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy11/uploads/2021/12/logo.png","height":133,"width":434,"orientation":"landscape"}},"compat":{"item":"","meta":""}}]} /-->