<?php
/**
 * Title: 网站头部模式3
 * Slug: smartenterprise/webhead3
 * Categories: webhead
 * Block Types: core/template-part
 * Viewport Width: 1400
 */
?>
<!-- wp:themepark-block/themepark-header {"headinfo":[{"module":"2","navtext":16,"navb":false,"navpd":25,"navc1":"#2e251d","navc2":"#ffffff","navc3":"#cda274","navc4":"","navc5":"#ffffff","navc6":"","topc1":"#cda274","topc2":"#232323","topf":14,"seach1":"","seach2":""}],"top_left_txt1":[{"text":"欢迎来到THEMEPARK家装！","url":"","icon":"fas fa-brush"},{"text":"微信同号：188-12345-6789","url":"","icon":"fab fa-weixin"}],"top_left_txt2":[{"text":"售前咨询：0731-234567","url":"","icon":"fas fa-phone-square"},{"text":"售后咨询：0731-56789123","url":"","icon":"fas fa-phone-square"}],"testnavmenue":"首页\n整装定制\n装修工艺\n家装百科\n精选案例\n关于我们\n联系我们","headinfotop":true,"logoimg":[{"uploading":false,"date":1624354242000,"filename":"pclogo.jpg","menuOrder":0,"uploadedTo":24,"type":"image","subtype":"jpeg","id":3892,"title":"pclogo","url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy7/uploads/2021/06/pclogo.jpg","link":"<?php echo get_bloginfo('home');?>/?attachment_id=3892","alt":"","author":"1","description":"","caption":"","name":"pclogo","status":"inherit","modified":1624354242000,"mime":"image/jpeg","icon":"<?php echo get_bloginfo('home');?>/wp-includes/images/media/default.png","dateFormatted":"2021年6月22日","nonces":{"update":"8c33b4a717","delete":"f17e9e28e8","edit":"11c5536465"},"editLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=3892\u0026action=edit","meta":false,"authorName":"admin","authorLink":"<?php echo get_bloginfo('home');?>/wp-admin/profile.php","uploadedToTitle":"网站头部模板","uploadedToLink":"<?php echo get_bloginfo('home');?>/wp-admin/post.php?post=24\u0026action=edit","filesizeInBytes":6758,"filesizeHumanReadable":"7 KB","context":"","height":91,"width":291,"orientation":"landscape","sizes":{"thumbnail":{"height":91,"width":150,"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy7/uploads/2021/06/pclogo-150x91.jpg","orientation":"landscape"},"full":{"url":"http://data.themepark.com.cn/2021/n/smartenterprise_data/qy7/uploads/2021/06/pclogo.jpg","height":91,"width":291,"orientation":"landscape"}},"compat":{"item":"","meta":""}}]} /-->